#配置启动端口以及项目名
server:
  port: 8082
  servlet:
    context-path: /liuyu
#配置数据库信息
spring:
  security:
    user:
      name: liuyu
      password: liuyu0113
  datasource:
    url: jdbc:mysql://49.234.102.27:3306/myblog?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: liuyu0113
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    hikari:
#      最小连接数
      minimum-idle: 5
#      最大连接数
      maximum-pool-size: 15
      connection-init-sql:
#        连接时初始化执行的SQL
        select 1 from hitokoto
      connection-test-query:
#        连接时测试执行的SQL
        select 1 from hitokoto
      connection-timeout: 240000
  redis:
    host: 49.234.102.27
    # Redis数据库索引（默认为0）
    database: 0
    port: 6379
    password: liuyu0113
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 16
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 16
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
    client-name: mall
    timeout: 5000
mybatis-plus:
  mapper-locations: classpath*:com/liuyu/mall/repository/mapper/*.xml
  type-aliases-package: com.liuyu.mall.domain
  global-config:
    banner: false
  configuration:
#    控制台输出执行的SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#Redis的配置